name: Outputs Github Action Practice
on: push
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - id: value_storage
        run: echo "message=Hello from Step 1" >> $GITHUB_OUTPUT
      - name: Output the message
        run: echo "${{ steps.value_storage.outputs.message }}"
