name: Use action.yml files
on: push
jobs:
  use-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Run JS action
        uses: ./JS-custom-action

  use-composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Run composite action
        uses: ./Composite-action
